import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "@/provider/Providers";
export const metadata: Metadata = {
  title: "The Sourob | Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main className="w-full  bg-purple-50">
            {children}
            <Toaster />
          </main>
        </Providers>
      </body>
    </html>
  );
}
